export const MUSICIANS = [
  {
    id: 1,
    name: 'James Kariuki',
    img: 'https://images.unsplash.com/photo-1598367833332-d8f926aa2c65?q=80&w=800',
    location: 'Nairobi',
    genre: 'Jazz & Afro-Soul',
    tags: ['Weddings', 'Hotels', 'Corporate'],
    price: 8000,
    rating: 5.0,
    reviews: 48,
    bio: 'With over 10 years of performing across Nairobi\'s top venues, James blends jazz improvisation with afro-soul rhythms. He has headlined events at Tribe Hotel, Villa Rosa Kempinski, and Safari Park Hotel.',
    experience: '10+ years',
    languages: ['English', 'Swahili'],
    responseTime: '< 1 hour',
    completionRate: '99%',
  },
  {
    id: 2,
    name: 'Amina Hassan',
    img: 'https://images.unsplash.com/photo-1549413182-07358db225d6?q=80&w=800',
    location: 'Mombasa',
    genre: 'Classical & Contemporary',
    tags: ['Restaurants', 'Private'],
    price: 12000,
    rating: 4.9,
    reviews: 31,
    bio: 'Trained at the Kenya Conservatoire of Music, Amina delivers classical sophistication with a contemporary flair. Her performances at Sarova Whitesands and Diani Reef Resort have made her the go-to musician on the Coast.',
    experience: '8 years',
    languages: ['English', 'Swahili', 'Arabic'],
    responseTime: '< 2 hours',
    completionRate: '100%',
  },
  {
    id: 3,
    name: 'Peter Ochieng',
    img: 'https://images.unsplash.com/photo-1552033009-4050e633d36b?q=80&w=800',
    location: 'Nairobi',
    genre: 'Bossa Nova & Latin',
    tags: ['Restaurants', 'Lounges'],
    price: 6500,
    rating: 4.8,
    reviews: 22,
    bio: 'Peter studied music in Brazil for three years, returning to Nairobi with an infectious love for bossa nova and Latin jazz. His laid-back style creates the perfect atmosphere for upscale dining.',
    experience: '6 years',
    languages: ['English', 'Swahili', 'Portuguese'],
    responseTime: '< 3 hours',
    completionRate: '97%',
  },
  {
    id: 4,
    name: 'Grace Wambui',
    img: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?q=80&w=800',
    location: 'Kisumu',
    genre: 'Gospel & R&B',
    tags: ['Weddings', 'Church'],
    price: 9500,
    rating: 5.0,
    reviews: 57,
    bio: 'Grace is one of Kenya\'s most celebrated gospel saxophonists, known for her spirit-filled performances that move audiences to tears. She has performed at weddings and church events across 5 counties.',
    experience: '12 years',
    languages: ['English', 'Swahili', 'Luo'],
    responseTime: '< 1 hour',
    completionRate: '100%',
  },
  {
    id: 5,
    name: 'Michael Otieno',
    img: 'https://images.unsplash.com/photo-1514525253361-bee8718a300c?q=80&w=800',
    location: 'Nairobi',
    genre: 'Neo-Soul & Funk',
    tags: ['Corporate', 'Hotels', 'Lounges'],
    price: 10000,
    rating: 4.9,
    reviews: 35,
    bio: 'Michael is a versatile neo-soul saxophonist who has toured with major Kenyan artists. His smooth, groovy style is perfect for corporate events seeking a modern, polished sound.',
    experience: '9 years',
    languages: ['English', 'Swahili'],
    responseTime: '< 2 hours',
    completionRate: '98%',
  },
  {
    id: 6,
    name: 'Diana Njeri',
    img: 'https://images.unsplash.com/photo-1550747540-c02073932a3f?q=80&w=800',
    location: 'Nakuru',
    genre: 'Afrobeat & Contemporary',
    tags: ['Weddings', 'Private', 'Festivals'],
    price: 7500,
    rating: 4.7,
    reviews: 19,
    bio: 'Diana brings the energy of afrobeat to every performance. Young, dynamic, and full of charisma, she is quickly becoming one of the most sought-after musicians in the Rift Valley region.',
    experience: '4 years',
    languages: ['English', 'Swahili', 'Kikuyu'],
    responseTime: '< 4 hours',
    completionRate: '96%',
  },
];

export const GENRES = ['All', 'Jazz', 'Classical', 'Gospel', 'Afrobeat', 'Neo-Soul', 'Bossa Nova', 'R&B'];
export const LOCATIONS = ['All Cities', 'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'];
export const EVENT_TYPES = ['All Events', 'Wedding', 'Corporate', 'Restaurant', 'Hotel Lounge', 'Private Party', 'Festival'];
