export const MUSICIANS = [
  {
    id: 1,
    name: 'Caleb Kalama',
    instrument: 'Saxophone',
    img: 'https://res.cloudinary.com/my-law-firm/image/upload/v1778701785/There_s_nothing_quite_like_the_synergy_of_a_live_performance_captured_forever._Huge_thank_you_t_z0q7me.jpg',
    location: 'Nairobi',
    genre: 'Jazz & Afro-Soul',
    tags: ['Weddings', 'Hotels and Restaurants', 'Corporate Events', 'Private Parties'],
    price: 9000,
    rating: 5.0,
    reviews: 48,
    bio: 'With over 4 years of performing across Nairobi\'s top venues, James blends jazz improvisation with afro-soul rhythms. He has headlined events at Tribe Hotel, Villa Rosa Kempinski, and Safari Park Hotel.',
    experience: '4 years',
    languages: ['English', 'Swahili'],
    responseTime: '< 1 hour',
    completionRate: '99%',
    performanceVideos: [
      'https://res.cloudinary.com/my-law-firm/video/upload/v1778701875/Live_sax_pure_vibes_Your_wedding_deserves_this_kind_of_a_vibe_..lets_make_it_happen_saxo_zslx3g.mp4',
    ],
  },
  {
    id: 2,
    name: 'Grace Wambui',
    instrument: 'Violin',
    img: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=800',
    location: 'Nairobi',
    genre: 'Classical & Contemporary',
    tags: ['Weddings', 'Corporate Events', 'Private Dinner'],
    price: 9000,
    rating: 4.9,
    reviews: 57,
    bio: 'Grace is one of Kenya\'s most celebrated violinists, known for her elegant performances at high-end corporate events and intimate wedding ceremonies.',
    experience: '5 years',
    languages: ['English', 'Swahili'],
    responseTime: '< 1 hour',
    completionRate: '100%',
    performanceVideos: [
      'https://res.cloudinary.com/my-law-firm/video/upload/v1778701792/offthemarket_proposeday_love_saxophone_suprise_happygirlsaretheprettiestgirls_woodwinds_gvnvbl.mp4'
    ],
  },
  {
    id: 3,
    name: 'Elite Jazz Duo',
    instrument: 'Band',
    img: 'https://images.unsplash.com/photo-1707944495849-8a6e045d44e1?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fHNheGFwaG9uZSUyMGFydGlzdHxlbnwwfHwwfHx8MA%3D%3D',
    location: 'Nairobi',
    genre: 'Jazz & Swing',
    tags: ['Corporate Events', 'Hotels and Restaurants', 'Rooftop Events'],
    price: 9000,
    rating: 4.8,
    reviews: 32,
    bio: 'A sophisticated duo specializing in ambient jazz, perfect for cocktail hours and upscale restaurant nights.',
    experience: '6 years',
    languages: ['English'],
    responseTime: '< 2 hours',
    completionRate: '98%',
    performanceVideos: [],
  },
  {
    id: 4,
    name: 'Sarah Song',
    instrument: 'Vocalist',
    img: 'https://media.istockphoto.com/id/1284319686/photo/black-female-singer-singing-into-microphone-in-recording-studio.webp?a=1&b=1&s=612x612&w=0&k=20&c=re59dqr_ZWWjIKJPaJwOi4DgfIs_L1ySlDcxy0ssEeo=',
    location: 'Mombasa',
    genre: 'Soul & Pop',
    tags: ['Weddings', 'Beach Events', 'Private Parties'],
    price: 9000,
    rating: 4.7,
    reviews: 25,
    bio: 'Sarah is a soulful vocalist whose voice captures the essence of coastal vibes. Perfect for sunset sessions and weddings.',
    experience: '5 years',
    languages: ['English', 'Swahili'],
    responseTime: '< 1 hour',
    completionRate: '100%',
    performanceVideos: [],
  },
  {
    id: 5,
    name: 'David Keyz',
    instrument: 'Pianist',
    img: 'https://media.istockphoto.com/id/2166312106/photo/playing-keyboard-in-studio-with-midi-controller-and-faders.webp?a=1&b=1&s=612x612&w=0&k=20&c=PXmx9ISGx_dLJEquL64VWVgI9j8fL11vYpkTlgdpxI4=',
    location: 'Nairobi',
    genre: 'Classical & Neo-Soul',
    tags: ['Hotels and Restaurants', 'Private Dinner', 'Corporate Events'],
    price: 9000,
    rating: 4.9,
    reviews: 42,
    bio: 'A master of the keys, David provides an elegant atmosphere for any high-class event.',
    experience: '4 years',
    languages: ['English'],
    responseTime: '< 1 hour',
    completionRate: '100%',
    performanceVideos: [],
  }
];

export const GENRES = ['All', 'Jazz', 'Classical', 'Gospel', 'Afrobeat', 'Soul', 'Pop', 'Contemporary'];
export const INSTRUMENTS = ['All', 'Saxophone', 'Violin', 'Band', 'Vocalist', 'Pianist'];
export const LOCATIONS = ['All Cities', 'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'];
export const EVENT_TYPES = ['Hotel Entertainment', 'Restaurant Night', 'Birthday', 'Wedding', 'Corporate Event', 'Private Dinner', 'Rooftop / Lounge Night', 'Other'];
